services:
  - type: web
    name: petpath-backend
    env: node
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    rootDirectory: main 
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        value: "mongodb+srv://yaelle:petpath2024@cluster0.dnotx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
